### ISSUE TITLE
'InferenceCMI' object has no attribute 'eval_log_prob_from_dist'

### ISSUE THREAD

**Issue by 945716994** [wangzizhao/CausalDynamicsLearning#4]
```
Traceback (most recent call last):
  File "/home/wjg/code/CDL/cdl/model/inference_cmi.py", line 792, in reward
    full_log_prob, causal_log_prob = self.eval_log_prob_from_dist(next_obses, pred_next_dist)
  File "/home/wjg/anaconda3/envs/tdmpc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'InferenceCMI' object has no attribute 'eval_log_prob_from_dist'
```

**Comment by wangzizhao** [comment]
Thanks for pointing it out, and it should be fixed by the latest commit. Let me know if you still have any problems running the code.
